### ISSUE TITLE
Add support for exposing kepler.gl at external IP

### ISSUE THREAD

**Issue by ghost** [crazycapivara/docker-kepler.gl#1]
Great initiative. Is it possible to add the possibily of passing -host paramter. As far as I understand the current image only exposes kepler at localhost or 127.0.0.1

**Comment by crazycapivara** [comment]
Hi,
it uses `0.0.0.0` as host so that it is available at external IP.
Furthermore, you can pull the latest image or use the `nginx` tag to get kepler.gl served by _nginx_:

`docker run -p 8080:80 --name kepler -d -e MapboxAccessToken="yourAccessToken" crazycapivara/kepler.gl`

Note the port change inside the container, it changed to 80!

**Comment by ghost** [comment]
Are you sure the -host 0.0.0.0 argument is enough. I'm no expert, but I'm only able to reach this from localhost. A quick web search says something about this is expected - and you should add --public parameter to expose it on external interface.

https://github.com/webpack/webpack-dev-server/releases/tag/v2.4.3

**Comment by crazycapivara** [comment]
Did you test the latest image using _nginx_ instead of the _webpack-dev-server_?

`docker pull crazycapivara/kepler.gl:nginx` (same as latest now)

`docker run -p 7180:80 --name kepler-nginx -d -e MapboxAccessToken="yourToken" crazycapivara/kepler.gl:nginx`

**Comment by crazycapivara** [comment]
If you want to use the _webpack-dev-server_ you must explicitly use the tag. Moreover, you can overwrite the default startup command like this:

`docker run -p 7180:90 --name kepler-webpack -d -e MapboxAccessToken="yourToken" crazycapivara/kepler.gl:webpack-dev-server webpack-dev-server --progress --public --port 90 --host 0.0.0.0`

**Comment by ghost** [comment]
Works fine with nginx version, thanks.
