### ISSUE TITLE
Request are not redirected to port

### ISSUE THREAD

**Issue by francois-baptiste** [crazycapivara/docker-kepler.gl#6]
When executing this exemple :
`docker run --name kepler.gl -p 8080:80 -d crazycapivara/kepler.gl`
in my web browser request are linked to port 80 and not 8080.

For instance:
http://localhost/sockjs-node/info?t=1585238599032
instead of
http://localhost:8080/sockjs-node/info?t=1585238599032

**Comment by crazycapivara** [comment]
@francois-baptiste 
`-p 8080:80` is just the docker port mapping.
Maybe on your machine 8080 ist already in use, so just map the container to another port like 8181 or whatever.

**Comment by francois-baptiste** [comment]
The problem do not come from the allocation of the destination port.
The issue is the same for port 8081 or whatever...

The issue comes from some hardlink to localhost:80 in the uri of some js dependency when served from the container and then when I browse the site from the host machine it fails...

**Comment by crazycapivara** [comment]
Hm
I cannot reproduce your issue.

you may overwrite the startup command when starting the container.

```
docker run --rm --name kepler.gl -p 8080:8080 \
  crazycapivara/kepler.gl webpack-dev-server --progress --port 8080 --host 0.0.0.0

```
This is the current startup cmd:

```
CMD ["webpack-dev-server", "--progress", "--port", "80", "--host", "0.0.0.0"]
```

**Comment by francois-baptiste** [comment]
Yes this do the trick. Thank you very much!

To reproduce the issue:
`docker run --name kepler.gl -p 8080:80 -d crazycapivara/kepler.gl`
Then open localhost:8080 with debug console in your browser.

![image](https://user-images.githubusercontent.com/7817985/77684056-ac52ac00-6f99-11ea-9224-43c4a42e6d69.png)
